
version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  ied_nginx_fileserver:
    build: ./fileserver
    restart: always
    ports:
      - "8081:80"
    volumes:
      - /home/wamaitha/MADVISION/clips_output:/var/www/html/videos

volumes:
  rabbitmq_data:
